#!/usr/bin/env bash

set -o errexit
set -o nounset

worker_ready() {
    celery -A app.celery inspect ping
}

until worker_ready; do
  >&2 echo 'Waiting for Celery workers to be ready...'
  sleep 1
done
>&2 echo 'Celery workers ready'

celery -A app.celery  \
    --broker="${CELERY_BROKER_URL}" \
    flower